# Generated by Django 4.0.5 on 2022-06-24 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('update_date', models.DateTimeField(auto_created=True, auto_now=True)),
                ('doc_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('doc_text', models.TextField(max_length=5000000.0)),
                ('entities', models.TextField(max_length=2000)),
            ],
        ),
    ]
